### ISSUE TITLE
 Use in gulp 4 is not possible.

### ISSUE THREAD

**Issue by moacir-selinger** [nikhilmodak/gulp-ngdocs#129]
Due to the evolution of our project, it was necessary to update the version of our gulp to ˆ4.x.x and the version of our Nodejs to ˆ12.x.x.

After these updates, the following error related to gulp-ngdocs occurs:
`
ReferenceError: primordials is not defined
    at fs.js:40:5
    at req_ (/Users/selinger/Documents/controlle/zze-front/node_modules/natives/index.js:143:24)
    at Object.req [as require] (/Users/selinger/Documents/controlle/zze-front/node_modules/natives/index.js:55:10)
    at Object.<anonymous> (/Users/selinger/Documents/controlle/zze-front/node_modules/gulp-ngdocs/node_modules/graceful-fs/fs.js:1:37)
    at Module._compile (internal/modules/cjs/loader.js:1236:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1257:10)
    at Module.load (internal/modules/cjs/loader.js:1085:32)
    at Function.Module._load (internal/modules/cjs/loader.js:950:14)
    at Module.require (internal/modules/cjs/loader.js:1125:19)
    at require (internal/modules/cjs/helpers.js:75:18)
`

I would be very grateful if a new version was made available for gulp 4, as the whole doc of our project depends on it to work.

Thank you!

**Comment by IvanGarzon** [comment]
@moacir-selinger I don't know if this helps but you can add this to your package.json file.

```
{
  "name": "my-app", 
  "scripts": {
    "preinstall": "npx npm-force-resolutions"
  },
  "resolutions": {
    "graceful-fs": "^4.2.4"
  }
}
```
