### ISSUE TITLE
TypeError: Cannot read property 'loadDefaults' of undefined

### ISSUE THREAD

**Issue by xduseko** [nikhilmodak/gulp-ngdocs#21]
`gulp.task('ngdocs', [], function () {`
`	var gulpDocs = require('gulp-ngdocs');`
`	return gulp.src('app/**/*.js')`
`		.pipe(gulpDocs.process())`
`		.pipe(gulp.dest('./ngdocs'));`
`});`

`TypeError: Cannot read property 'loadDefaults' of undefined`
`    at Object.processDoc [as process] (C:\Users\odusek\IdeaProjects\iprace-front-end-angular\node_modules\gulp-ngdocs\index.js:95:12)`
`    at Gulp.<anonymous> (C:\Users\odusek\IdeaProjects\iprace-front-end-angular\gulpfile.js:397:18)`
`    at module.exports (C:\Users\odusek\IdeaProjects\iprace-front-end-angular\node_modules\gulp\node_modules\orchestrator\lib\runTask.js:34:7)`
`    at Gulp.Orchestrator._runTask (C:\Users\odusek\IdeaProjects\iprace-front-end-angular\node_modules\gulp\node_modules\orchestrator\index.js:273:3)`
`    at Gulp.Orchestrator._runStep (C:\Users\odusek\IdeaProjects\iprace-front-end-angular\node_modules\gulp\node_modules\orchestrator\index.js:214:10)`
`    at Gulp.Orchestrator.start (C:\Users\odusek\IdeaProjects\iprace-front-end-angular\node_modules\gulp\node_modules\orchestrator\index.js:134:8)`
`    at C:\Users\odusek\AppData\Roaming\npm\node_modules\gulp\bin\gulp.js:129:20`
`    at process._tickCallback (node.js:442:13)`
`    at Function.Module.runMain (module.js:499:11)`
`    at startup (node.js:119:16)`

**Comment by macdaddy** [comment]
Same issue here:

```
gulp.task('ngdocs', function () {
  var gulpDocs = require('gulp-ngdocs');
  return gulp.src('public/**/*.js')
  .pipe(gulpDocs.process())
  .pipe(gulp.dest('./ngdocs'));
});
```

```
✗ gulp ngdocs
[13:58:36] Using gulpfile ~/vcs/git/myproject/gulpfile.js
[13:58:36] Starting 'ngdocs'...
[13:58:37] 'ngdocs' errored after 690 ms
[13:58:37] TypeError: Cannot read property 'loadDefaults' of undefined
    at Object.processDoc [as process] (/Users/david/vcs/git/myproject/node_modules/gulp-ngdocs/index.js:95:12)
    at Gulp.<anonymous> (/Users/david/vcs/git/myproject/gulp/build.js:97:18)
    at module.exports (/Users/david/vcs/git/myproject/node_modules/gulp/node_modules/orchestrator/lib/runTask.js:34:7)
    at Gulp.Orchestrator._runTask (/Users/david/vcs/git/myproject/node_modules/gulp/node_modules/orchestrator/index.js:273:3)                                                                                                                                                                                                                                                                         
    at Gulp.Orchestrator._runStep (/Users/david/vcs/git/myproject/node_modules/gulp/node_modules/orchestrator/index.js:214:10)
    at Gulp.Orchestrator.start (/Users/david/vcs/git/myproject/node_modules/gulp/node_modules/orchestrator/index.js:134:8)
    at /usr/local/lib/node_modules/gulp/bin/gulp.js:129:20
    at process._tickCallback (node.js:442:13)
    at Function.Module.runMain (module.js:499:11)
    at startup (node.js:119:16)
```

**Comment by MikaAK** [comment]
+1 Same issue here, is there a temporary way I can generate docs (without grunt)

**Comment by PabloDeGrote** [comment]
I just dived into the code (index.js), and it seems like there is no fallback to the variable ``opts``

The module; node.extend expects an object and is now getting undefined.

Quick fix (to get bulding, notice the ``{}`` in process):
````
gulp.task('ngdocs', function () {
  var gulpDocs = require('gulp-ngdocs');
  return gulp.src('public/**/*.js')
  .pipe(gulpDocs.process({}))
  .pipe(gulp.dest('./ngdocs'));
});
````

Fix for this module:
````
function processDoc(opts) {
 opts = opts || {};
````

**Comment by rmpietro** [comment]
Had the same problem. The fix you presented did the trick! Thanks a lot.

**Comment by revspringjake** [comment]
Heres another quick patch until it's fixed...
You can just pass in a blank object.

  gulp.task('makeDocs', [], function () {
    var gulpDocs = require('gulp-ngdocs');
    var options = {};
    return gulp.src( productionScripts )
    .pipe(gulpDocs.process( options ))
    .pipe(gulp.dest('public/test/docs'));
  });
