### ISSUE TITLE
Unrecoverable error

### ISSUE THREAD

**Issue by hanneskaeufler** [nikhilmodak/gulp-ngdocs#32]
When I run ngdocs over a set of folders in my app, eventually I got to this error.
I GUESS it is because an annotation like

```
/**
 * @param {array|*} foo bar
 */
```

which I encountered before. But this error does not lead me at all to a file or line in the code where I should fix the invalid docblock.

```
/vagrant/xxx/node_modules/gulp-ngdocs/src/ngdoc.js:438
          self.type = match[1];
                           ^
TypeError: Cannot read property '1' of null
    at flush (/vagrant/xxx/node_modules/gulp-ngdocs/src/ngdoc.js:438:28)
    at /vagrant/xxx/node_modules/gulp-ngdocs/src/ngdoc.js:359:9
    at Array.forEach (native)
    at Object.Doc.parse (/vagrant/xxx/node_modules/gulp-ngdocs/src/ngdoc.js:355:31)
    at /vagrant/xxx/node_modules/gulp-ngdocs/src/reader.js:49:99
    at Array.forEach (native)
    at processJsFile (/vagrant/xxx/node_modules/gulp-ngdocs/src/reader.js:34:9)
    at Object.process (/vagrant/xxx/node_modules/gulp-ngdocs/src/reader.js:17:5)
    at DestroyableTransform.transformFunction [as _transform] (/vagrant/xxx/node_modules/gulp-ngdocs/index.js:208:14)
    at DestroyableTransform.Transform._read (/vagrant/xxx/node_modules/gulp-ngdocs/node_modules/through2/node_modules/readable-stream/lib/_stream_transform.js:184:10)
```

**Comment by andyperlitch** [comment]
So to be clear, you're asking for better reporting of where an error is happening, correct? If so, I also agree with you, it should be more obvious

**Comment by hanneskaeufler** [comment]
Yep exactly! I have no idea where to look at for the malformed comment from the stacktrace. :+1:

**Comment by tregusti** [comment]
I ran into this too, and the problem isn't the reporting per se, but that the tool crashes. It is really error handling that should be added.

Is @hanneskaeufler is correct in that multiple types are not supported for `@param`?
