### ISSUE TITLE
can't catch parse error in stream

### ISSUE THREAD

**Issue by reykjavikingur** [nikhilmodak/gulp-ngdocs#74]
I'm finding it really useful to run `gulp-ngdocs` as part of a watch task, so whenever I change the doc comments in my source files, the update takes effect immediately and refreshes my local server. I generally make my gulp tasks handle stream errors gracefully, because I don't want ngdoc syntax errors to crash my watches. This works fine some of the time, but I've found many types of common ngdoc syntax errors that cause `gulp-ngdocs` to throw exceptions rather than emitting stream errors.

Naturally, I can always fix the syntax error, but since the exception forces the process to exit, I have to restart the gulp watch task every time, and that can become very inconvenient.

Here's a simple example that I constructed:

Contents of `src/bad.js`:
```
/**
 * @ngdoc function
 * @name bad
 * @param {Object} record The data stuff
 * @returns {Object}
 */
function bad() {

}
```

Gulp task:
```
var gulp = require('gulp');
var gutil = require('gulp-util');
var doc = require('gulp-ngdocs');
gulp.task('bad', [], function () {
	return gulp.src('src/bad.js')
		.pipe(doc.process().on('error', gutil.log))
		.pipe(gulp.dest('dist'))
		.on('error', gutil.log);
});
```

Result of running `gulp bad`:
```
[15:16:28] Starting 'bad'...

C:\ProjectCode\node\gulp-ngdocs-error-handler\node_modules\gulp-ngdocs\src\ngdoc.js:437
            throw new Error("Not a valid 'returns' format: " + text + ' (found
                  ^
Error: Not a valid 'returns' format: {Object} (found in: C:\ProjectCode\node\gulp-ngdocs-error-handler\src\bad.js:1)
    at flush (C:\ProjectCode\node\gulp-ngdocs-error-handler\node_modules\gulp-ngdocs\src\ngdoc.js:437:19)
    at Object.Doc.parse (C:\ProjectCode\node\gulp-ngdocs-error-handler\node_modules\gulp-ngdocs\src\ngdoc.js:394:5)
    at C:\ProjectCode\node\gulp-ngdocs-error-handler\node_modules\gulp-ngdocs\src\reader.js:49:99
    at Array.forEach (native)
    at processJsFile (C:\ProjectCode\node\gulp-ngdocs-error-handler\node_modules\gulp-ngdocs\src\reader.js:34:9)
    at Object.process (C:\ProjectCode\node\gulp-ngdocs-error-handler\node_modules\gulp-ngdocs\src\reader.js:17:5)
    at DestroyableTransform.transformFunction [as _transform] (C:\ProjectCode\node\gulp-ngdocs-error-handler\node_modules\gulp-ngdocs\index.js:204:14)
    at DestroyableTransform.Transform._read (C:\ProjectCode\node\gulp-ngdocs-error-handler\node_modules\gulp-ngdocs\node_modules\through2\node_modules\readable-stream\lib\_stream_transform.js:184:10)
    at DestroyableTransform.Transform._write (C:\ProjectCode\node\gulp-ngdocs-error-handler\node_modules\gulp-ngdocs\node_modules\through2\node_modules\readable-stream\lib\_stream_transform.js:172:12)
    at doWrite (C:\ProjectCode\node\gulp-ngdocs-error-handler\node_modules\gulp-ngdocs\node_modules\through2\node_modules\readable-stream\lib\_stream_writable.js:237:10)
```

And then the process exits, thus killing my watch. Can this type of error be made to emit a stream event rather than throw an exception?

**Comment by tunurgitr** [comment]
At the risk of being late to the game: +1

**Comment by jongunter** [comment]
Does anyone know of a workaround here?

**Comment by ghost** [comment]
So there isn't a workaround for this yet?

**Comment by ghost** [comment]
Created a PR: #117 - This at least addresses the `Error`s that come from `transformFunction` and `flushFunction`, allowing end users to run `gulp-ngdocs` in this type of format:

``` js
gulp.task('ngDocs', [], function() {
  var self = this;
  var docs = ngDocs.process();
  docs.on('error', function(err) {
    gutil.log(err);
    docs.end();
  });
  return gulp.src('**/*.js')
    .pipe(docs)
    .pipe(gulp.dest('./docs'));
});
```
