### ISSUE TITLE
gulp-ngdocs doesen't show enough info on errors

### ISSUE THREAD

**Issue by marcoturi** [nikhilmodak/gulp-ngdocs#83]
Hi,
i'm using this code in this gulpfile.js to run ngdocs:

```gulp.task('ngdocs', [], function () {
    return gulp.src(paths.scripts)
        .pipe(gulpDocs.process({
            html5Mode: false,
            startPage: '/api'
        }))
        .pipe(gulp.dest('./www/docs'));
});```

It works but i don't get any info when a file throw an error. For example:
```
[Error: Don't know how to format @ngdoc: method]
events.js:85
      throw er; // Unhandled 'error' event
            ^
Error: Don't know how to format @ngdoc: method
    at Object.<anonymous> (C:\Users\marco\myapp\node_modules\gulp-ngdocs\src\ngdoc.js:527:15)
    at Object.<anonymous> (C:\Users\marco\myapp\node_modules\gulp-ngdocs\src\ngdoc.js:528:10)
    at Object.DOM.text (C:\Users\marco\myapp\node_modules\gulp-ngdocs\src\dom.js:67:15)
    at Object.DOM.tag (C:\Users\marco\myapp\node_modules\gulp-ngdocs\src\dom.js:110:10)
    at Object.DOM.h (C:\Users\marco\myapp\node_modules\gulp-ngdocs\src\dom.js:149:12)
    at Object.Doc.html (C:\Users\marco\myapp\node_modules\gulp-ngdocs\src\ngdoc.js:505:9)
    at C:\Users\marco\myapp\node_modules\gulp-ngdocs\index.js:225:38
    at Array.forEach (native)
    at DestroyableTransform.flushFunction [as _flush] (C:\Users\marco\myapp\node_modules\gulp-ngdocs\index.js:216:21)
    at DestroyableTransform.<anonymous> (C:\Users\marco\myapp\node_modules\gulp-ngdocs\node_modules\through2\node_modules\readable-stream\lib\_stream_transform.js:135:12)
    at DestroyableTransform.g (events.js:199:16)
    at DestroyableTransform.emit (events.js:129:20)
    at finishMaybe (C:\Users\marco\myapp\node_modules\gulp-ngdocs\node_modules\through2\node_modules\readable-stream\lib\_stream_writable.js:371:12)
    at endWritable (C:\Users\marco\myapp\node_modules\gulp-ngdocs\node_modules\through2\node_modules\readable-stream\lib\_stream_writable.js:378:3)
    at DestroyableTransform.Writable.end (C:\Users\marco\myapp\node_modules\gulp-ngdocs\node_modules\through2\node_modules\readable-stream\lib\_stream_writable.js:356:5)
    at DestroyableTransform.onend (C:\Users\marco\myapp\node_modules\gulp\node_modules\vinyl-fs\node_modules\through2\node_modules\readable-stream\lib\_stream_readable.js:523:10)
```

My project contains >400 files, how i'm supposed to find the one the throw this error ?

**Comment by guicoma** [comment]
+1 
I've also stumbled upon this kind of situation. How can we debug this error?
